version: '3.8'

services:
  web:
    build: .
    ports:
      - "8443:8443"
    env_file:
      - postgres.env
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"