version: '3.8'

services:
  web:
    build: .
    ports:
      - "8443:8443"
    expose:
      - 8443
    env_file:
      - web.env
    restart: always
    networks:
      - ktor-network
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - db.env
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - ktor-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - ktor-network
#  test:
#    build:
#      context: .
#      dockerfile: Dockerfile.test
#    env_file:
#      - web.env
#    depends_on:
#      - web
#    networks:
#      - ktor-network
networks:
  ktor-network:
    driver: bridge